apiVersion: v1
kind: Secret
metadata:
  name: {{ include "projectname.fullname" . }}-secret
  # namespace: {{ include "projectname.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "projectname.fullname" . }}-secret
    app.kubernetes.io/component: {{ include "projectname.component" . }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
